p8105_hw2_jz3571
================
Junyan Zhu

``` r
library(tidyverse)
library(readxl)
```

# Problem 1

``` r
nyc_df = read_csv('./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv') %>% 
  janitor::clean_names() %>% 
  select(line:station_longitude, starts_with("route"), entry, exit_only, vending, entrance_type, ada) %>% 
  mutate(route8 = as.character(route8), route9 = as.character(route9), route10 = as.character(route10), route11 = as.character(route11)) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The date has 1868 rows and 20 columns and it contains variables: line,
station_name, station_latitude, station_longitude, route1, route2,
route3, route4, route5, route6, route7, route8, route9, route10,
route11, entry, exit_only, vending, entrance_type, ada. The above date
cleaning steps include selecting required variables, converting route
8-11 into character variables and converting entry variable from
chatacter variable to logic variable. These data are not tidy yet.

-   Number of Distint Stations

``` r
nyc_df %>% 
  select(station_name, line) %>% 
  distinct %>% 
  nrow()
```

    ## [1] 465

There are 465 distinct stations.

-   Number of Ada Compliant Stations

``` r
nyc_df %>% 
  filter(ada == 'TRUE') %>% 
  select(station_name, line) %>% 
  distinct %>% 
  nrow()
```

    ## [1] 84

There are 84 stations are ADA compliant

-   Number of stations without vending alowing entrance

``` r
nyc_df %>% 
  filter(vending == 'NO') %>% 
  pull(entry) %>% 
  mean()
```

    ## [1] 0.3770492

There are 37.7% of the entrances/exits without vending allow entrance.
